# Generated by Django 3.2.16 on 2022-11-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20221105_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=50)),
                ('reciever', models.CharField(max_length=50)),
            ],
        ),
    ]
