# Generated by Django 3.2.16 on 2022-11-05 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictures', '0011_auto_20221105_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_by',
        ),
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='message',
            name='recieved_by',
        ),
        migrations.AddField(
            model_name='message',
            name='recieved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='y', to=settings.AUTH_USER_MODEL),
        ),
    ]
